name: Deploy Intranet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install MkDocs Material
        run: pip install mkdocs-material

      - name: Build MkDocs
        run: mkdocs build

      - name: Copy site to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 192.168.1.48
          username: alvar
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "site/*"
          target: "/home/alvar/intranet-docs/site"

      - name: Restart Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 192.168.1.48
          username: alvar
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/alvar/intranet-docs
            docker compose down
            docker compose up -d
